language: python # why not

services:
 - docker

script:
 - docker build -t honeycombio/fluentd-honeycomb:1.${TRAVIS_BUILD_NUMBER} ./fluentd-hny-image

after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
   docker push honeycombio/fluentd-honeycomb:1.${TRAVIS_BUILD_NUMBER};
   fi

after_failure:
 - docker logs honeycombio/fluentd-honeycomb:1.${TRAVIS_BUILD_NUMBER}
